"""empty message

Revision ID: 43f94d00b9b3
Revises: 02e54ab59099
Create Date: 2023-11-01 07:58:29.129595

"""

# revision identifiers, used by Alembic.
revision = "43f94d00b9b3"
down_revision = "02e54ab59099"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
