"""empty message

Revision ID: 02e54ab59099
Revises: 0bbe9f2e35dc
Create Date: 2023-10-31 09:51:53.884061

"""

# revision identifiers, used by Alembic.
revision = "02e54ab59099"
down_revision = "0bbe9f2e35dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
