"""empty message

Revision ID: dab3cd304260
Revises: 
Create Date: 2023-12-02 12:28:25.031310

"""
import ormar
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dab3cd304260"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=True),
        sa.Column("owner_id", sa.String(length=200), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("model_id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=False),
        sa.Column("path", sa.String(length=100), nullable=True),
        sa.Column("parameters", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ml_models",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=200), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.String(length=200), nullable=False),
        sa.Column("parameters", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=False),
        sa.Column("result_type", sa.String(length=7), nullable=False),
        sa.Column("job", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
        sa.Column("dataset_id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("status", sa.String(length=300), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("metrics", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("files", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("parameters", sa.JSON(none_as_null=True), nullable=True),
        sa.ForeignKeyConstraint(["job"], ["jobs.id"], name="fk_results_jobs_id_job"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("results")
