"""empty message

Revision ID: 27c53c66e746
Revises: 64d8215d633a
Create Date: 2023-11-14 11:02:02.712837

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "27c53c66e746"
down_revision = "64d8215d633a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
