"""empty message

Revision ID: 65c2b22a6b96
Revises: 282e14b8e9d1
Create Date: 2023-11-02 13:25:38.114715

"""

# revision identifiers, used by Alembic.
revision = "65c2b22a6b96"
down_revision = "282e14b8e9d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
