"""empty message

Revision ID: 282e14b8e9d1
Revises: 206387717e5b
Create Date: 2023-11-02 13:19:15.617505

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "282e14b8e9d1"
down_revision = "206387717e5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "id",
        existing_type=sa.INTEGER(),
        type_=ormar.fields.sqlalchemy_uuid.CHAR(32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "id",
        existing_type=ormar.fields.sqlalchemy_uuid.CHAR(32),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
