"""empty message

Revision ID: 1db43412e9ca
Revises: 983074f56b96
Create Date: 2023-10-26 18:23:54.543929

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1db43412e9ca"
down_revision = "983074f56b96"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_name", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=200), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_models")
    # ### end Alembic commands ###
