"""empty message

Revision ID: 0bbe9f2e35dc
Revises: 9a8464a1824e
Create Date: 2023-10-31 09:50:56.175018

"""

# revision identifiers, used by Alembic.
revision = "0bbe9f2e35dc"
down_revision = "9a8464a1824e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
