"""empty message

Revision ID: cc9ba23f7ec0
Revises: a92ecef31133
Create Date: 2023-11-01 09:31:09.550398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc9ba23f7ec0"
down_revision = "a92ecef31133"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column("file_type", sa.String(length=5), nullable=False),
    )
    op.drop_constraint("datasets_unique_name_key", "datasets", type_="unique")
    op.drop_column("datasets", "unique_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "unique_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint("datasets_unique_name_key", "datasets", ["unique_name"])
    op.drop_column("datasets", "file_type")
    # ### end Alembic commands ###
