"""empty message

Revision ID: 206387717e5b
Revises: 33a769e2fffc
Create Date: 2023-11-02 06:53:56.077443

"""

# revision identifiers, used by Alembic.
revision = "206387717e5b"
down_revision = "33a769e2fffc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
