"""empty message

Revision ID: 5150ca9a7c17
Revises: 1c76d0aa39c2
Create Date: 2023-11-06 21:41:28.921219

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5150ca9a7c17"
down_revision = "1c76d0aa39c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "results",
        sa.Column("path", sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
