"""empty message

Revision ID: 76a34fb90f44
Revises: 73d7cbeeaef2
Create Date: 2023-11-14 19:49:19.143227

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76a34fb90f44"
down_revision = "73d7cbeeaef2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
