"""empty message

Revision ID: 869fc9dba991
Revises: 22fc199c8bbb
Create Date: 2023-11-05 10:49:21.389501

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "869fc9dba991"
down_revision = "22fc199c8bbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("model_id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    )
    op.drop_column("jobs", "model_name")
    op.alter_column(
        "ml_models",
        "id",
        existing_type=sa.INTEGER(),
        type_=ormar.fields.sqlalchemy_uuid.CHAR(32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ml_models",
        "id",
        existing_type=ormar.fields.sqlalchemy_uuid.CHAR(32),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "jobs",
        sa.Column(
            "model_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("jobs", "model_id")
    # ### end Alembic commands ###
