"""empty message

Revision ID: 983074f56b96
Revises: 819cbf6e030b
Create Date: 2023-10-26 18:15:21.033652

"""

# revision identifiers, used by Alembic.
revision = "983074f56b96"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
