"""empty message

Revision ID: 3d933c15dfd2
Revises: 76a34fb90f44
Create Date: 2023-11-14 19:55:13.048763

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d933c15dfd2"
down_revision = "76a34fb90f44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
