"""empty message

Revision ID: 9a8464a1824e
Revises: 49d2dde3b9ac
Create Date: 2023-10-31 09:40:20.603077

"""

# revision identifiers, used by Alembic.
revision = "9a8464a1824e"
down_revision = "49d2dde3b9ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
