"""empty message

Revision ID: 64d8215d633a
Revises: 1dc009b384f7
Create Date: 2023-11-14 11:01:00.999264

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64d8215d633a"
down_revision = "1dc009b384f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_models", sa.Column("parameters", sa.JSON(none_as_null=True), nullable=True),
    )
    op.add_column(
        "ml_models", sa.Column("layers", sa.JSON(none_as_null=True), nullable=True),
    )
    op.add_column("ml_models", sa.Column("private", sa.Boolean(), nullable=True))
    op.drop_constraint("ml_models_unique_name_key", "ml_models", type_="unique")
    op.drop_column("ml_models", "entry_point")
    op.drop_column("ml_models", "unique_name")
    op.add_column(
        "results", sa.Column("result_type", sa.String(length=7), nullable=False),
    )
    op.add_column(
        "results", sa.Column("metrics", sa.JSON(none_as_null=True), nullable=True),
    )
    op.add_column(
        "results", sa.Column("files", sa.JSON(none_as_null=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "files")
    op.drop_column("results", "metrics")
    op.drop_column("results", "result_type")
    op.add_column(
        "ml_models",
        sa.Column(
            "unique_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        "ml_models",
        sa.Column(
            "entry_point", sa.VARCHAR(length=200), autoincrement=False, nullable=True,
        ),
    )
    op.create_unique_constraint(
        "ml_models_unique_name_key", "ml_models", ["unique_name"],
    )
    op.drop_column("ml_models", "private")
    op.drop_column("ml_models", "layers")
    op.drop_column("ml_models", "parameters")
    # ### end Alembic commands ###
