"""empty message

Revision ID: 1c76d0aa39c2
Revises: 38fc6ba80cf5
Create Date: 2023-11-06 21:36:27.849582

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c76d0aa39c2"
down_revision = "38fc6ba80cf5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("results", sa.Column("status", sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "status")
    # ### end Alembic commands ###
