"""empty message

Revision ID: dfd63bb3a281
Revises: 1ff6775ead1c
Create Date: 2023-11-02 14:49:36.470972

"""

# revision identifiers, used by Alembic.
revision = "dfd63bb3a281"
down_revision = "1ff6775ead1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
