"""empty message

Revision ID: 33a769e2fffc
Revises: abbc002029f9
Create Date: 2023-11-01 19:39:30.896793

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33a769e2fffc"
down_revision = "abbc002029f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "results",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("job_id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("dataset_id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "ml_models",
        sa.Column("entry_point", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_models", "entry_point")
    op.drop_table("results")
    # ### end Alembic commands ###
