"""empty message

Revision ID: 49d2dde3b9ac
Revises: b703dae66fbd
Create Date: 2023-10-27 20:00:18.083952

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49d2dde3b9ac"
down_revision = "b703dae66fbd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "id",
        existing_type=sa.INTEGER(),
        type_=ormar.fields.sqlalchemy_uuid.CHAR(32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "id",
        existing_type=ormar.fields.sqlalchemy_uuid.CHAR(32),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
