"""empty message

Revision ID: 1dc009b384f7
Revises: b53f1beb7206
Create Date: 2023-11-07 12:06:02.763170

"""

# revision identifiers, used by Alembic.
revision = "1dc009b384f7"
down_revision = "b53f1beb7206"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
