"""empty message

Revision ID: 177c1b67883b
Revises: 1db43412e9ca
Create Date: 2023-10-27 16:20:10.015775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "177c1b67883b"
down_revision = "1db43412e9ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_name", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("datasets")
    # ### end Alembic commands ###
