"""empty message

Revision ID: 14a570bbeae3
Revises: 3d933c15dfd2
Create Date: 2023-11-15 10:26:12.850198

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14a570bbeae3"
down_revision = "3d933c15dfd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("parameters", sa.JSON(none_as_null=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "parameters")
    # ### end Alembic commands ###
