"""empty message

Revision ID: 22fc199c8bbb
Revises: 0a3c8adc2389
Create Date: 2023-11-02 19:45:14.501269

"""

# revision identifiers, used by Alembic.
revision = "22fc199c8bbb"
down_revision = "0a3c8adc2389"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
