"""empty message

Revision ID: 99e50031e5f3
Revises: 65c2b22a6b96
Create Date: 2023-11-02 13:36:36.147098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99e50031e5f3"
down_revision = "65c2b22a6b96"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "content_type",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "content_type",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
