"""empty message

Revision ID: 3bc5ea60a221
Revises: 14a570bbeae3
Create Date: 2023-11-16 08:13:27.803814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bc5ea60a221"
down_revision = "14a570bbeae3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
