"""empty message

Revision ID: 38fc6ba80cf5
Revises: 869fc9dba991
Create Date: 2023-11-05 11:10:15.171080

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38fc6ba80cf5"
down_revision = "869fc9dba991"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("model_name", sa.String(length=200), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "model_name")
    # ### end Alembic commands ###
