"""empty message

Revision ID: 509e0902d0c6
Revises: dfd63bb3a281
Create Date: 2023-11-02 14:54:19.821554

"""

# revision identifiers, used by Alembic.
revision = "509e0902d0c6"
down_revision = "dfd63bb3a281"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
