"""empty message

Revision ID: a92ecef31133
Revises: 43f94d00b9b3
Create Date: 2023-11-01 09:16:44.910133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a92ecef31133"
down_revision = "43f94d00b9b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("datasets", sa.Column("private", sa.Boolean(), nullable=True))
    op.add_column(
        "datasets",
        sa.Column("owner_id", sa.String(length=200), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "owner_id")
    op.drop_column("datasets", "private")
    # ### end Alembic commands ###
