"""empty message

Revision ID: 0a3c8adc2389
Revises: 509e0902d0c6
Create Date: 2023-11-02 14:56:10.016512

"""

# revision identifiers, used by Alembic.
revision = "0a3c8adc2389"
down_revision = "509e0902d0c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
