"""empty message

Revision ID: b53f1beb7206
Revises: 5150ca9a7c17
Create Date: 2023-11-06 22:11:25.675868

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b53f1beb7206"
down_revision = "5150ca9a7c17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "results",
        sa.Column("job", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    )
    op.create_foreign_key("fk_results_jobs_id_job", "results", "jobs", ["job"], ["id"])
    op.drop_column("results", "job_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "results",
        sa.Column("job_id", sa.CHAR(length=32), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_results_jobs_id_job", "results", type_="foreignkey")
    op.drop_column("results", "job")
    # ### end Alembic commands ###
