"""empty message

Revision ID: abbc002029f9
Revises: 6eca030f36af
Create Date: 2023-11-01 09:59:29.026090

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "abbc002029f9"
down_revision = "6eca030f36af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column("content_type", sa.String(length=30), nullable=False),
    )
    op.drop_column("datasets", "file_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "file_type",
            sa.VARCHAR(length=5),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("datasets", "content_type")
    # ### end Alembic commands ###
