"""empty message

Revision ID: 6eca030f36af
Revises: cc9ba23f7ec0
Create Date: 2023-11-01 09:31:45.261668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6eca030f36af"
down_revision = "cc9ba23f7ec0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "description",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "description",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    # ### end Alembic commands ###
