"""empty message

Revision ID: c55e7f69a64f
Revises: e1b15953b9c5
Create Date: 2024-06-17 15:37:55.780277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55e7f69a64f'
down_revision = 'e1b15953b9c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('dataset_type', sa.String(length=20), nullable=True))
    op.drop_column('results', 'dataset_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('dataset_path', sa.CHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('results', 'dataset_type')
    # ### end Alembic commands ###
