"""empty message

Revision ID: 966df6131348
Revises: 444a0bd6bcd9
Create Date: 2024-07-03 16:56:31.363832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966df6131348'
down_revision = '444a0bd6bcd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('environment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'environment')
    # ### end Alembic commands ###
