"""empty message

Revision ID: 5c0182cf2682
Revises: c443e8ac6fc1
Create Date: 2024-05-20 13:09:19.972272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0182cf2682'
down_revision = 'c443e8ac6fc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('model_branch', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('dataset_branch', sa.String(length=100), nullable=True))
    op.drop_column('jobs', 'repo_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('repo_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'dataset_branch')
    op.drop_column('jobs', 'model_branch')
    # ### end Alembic commands ###
