"""empty message

Revision ID: 6245751737fb
Revises: c55e7f69a64f
Create Date: 2024-06-29 20:02:23.984675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6245751737fb'
down_revision = 'c55e7f69a64f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('runner_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'runner_id')
    # ### end Alembic commands ###
