"""empty message

Revision ID: c443e8ac6fc1
Revises: 3a8b1015c4c7
Create Date: 2024-05-20 11:50:23.601538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c443e8ac6fc1'
down_revision = '3a8b1015c4c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('repo_hash', sa.String(length=100), nullable=True))
    op.drop_column('jobs', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'repo_hash')
    # ### end Alembic commands ###
