"""empty message

Revision ID: 43f7bf2f431a
Revises: 4bc5706cee1a
Create Date: 2024-05-15 17:06:37.054412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f7bf2f431a'
down_revision = '4bc5706cee1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
