"""empty message

Revision ID: 264183d9f757
Revises: 7de77be9749f
Create Date: 2024-06-03 12:21:01.740885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264183d9f757'
down_revision = '7de77be9749f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('clone_url', sa.String(length=300), nullable=False))
    op.drop_column('jobs', 'model_branch')
    op.add_column('ml_models', sa.Column('clone_url', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_models', 'clone_url')
    op.add_column('jobs', sa.Column('model_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'clone_url')
    # ### end Alembic commands ###
