"""empty message

Revision ID: 444a0bd6bcd9
Revises: 6245751737fb
Create Date: 2024-07-01 16:05:14.941738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444a0bd6bcd9'
down_revision = '6245751737fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
