"""empty message

Revision ID: 3a8b1015c4c7
Revises: 2eb26709b09e
Create Date: 2024-05-20 09:51:54.062323

"""
from alembic import op
import ormar
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b1015c4c7'
down_revision = '2eb26709b09e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_key_pairs', 'id',
               existing_type=sa.VARCHAR(length=200),
               type_=ormar.fields.sqlalchemy_uuid.CHAR(32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_key_pairs', 'id',
               existing_type=ormar.fields.sqlalchemy_uuid.CHAR(32),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
