"""empty message

Revision ID: 7de77be9749f
Revises: 5c0182cf2682
Create Date: 2024-06-02 17:40:23.707771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de77be9749f'
down_revision = '5c0182cf2682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('git_name', sa.String(length=200), nullable=False))
    op.drop_column('datasets', 'path')
    op.drop_column('jobs', 'dataset_branch')
    op.add_column('ml_models', sa.Column('git_name', sa.String(length=200), nullable=False))
    op.drop_column('ml_models', 'default_model')
    op.drop_column('ml_models', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('ml_models', sa.Column('default_model', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('ml_models', 'git_name')
    op.add_column('jobs', sa.Column('dataset_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('datasets', 'git_name')
    # ### end Alembic commands ###
