"""empty message

Revision ID: fe93c9f6090c
Revises: fd190ad76335
Create Date: 2024-06-07 16:30:37.579836

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'fe93c9f6090c'
down_revision = 'fd190ad76335'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dataset_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False))
    op.add_column('jobs', sa.Column('closed', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ready')
    op.drop_column('jobs', 'closed')
    op.drop_column('jobs', 'dataset_id')
    # ### end Alembic commands ###
