"""empty message

Revision ID: 4bc5706cee1a
Revises: dab3cd304260
Create Date: 2024-01-16 14:11:39.393434

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bc5706cee1a"
down_revision = "dab3cd304260"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_models", sa.Column("default_model", sa.String(length=200), nullable=False)
    )
    op.add_column("results", sa.Column("name", sa.String(length=200), nullable=False))
    op.add_column(
        "results", sa.Column("pretrained_model", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "results", sa.Column("predictions", sa.JSON(none_as_null=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "predictions")
    op.drop_column("results", "pretrained_model")
    op.drop_column("results", "name")
    op.drop_column("ml_models", "default_model")
    # ### end Alembic commands ###
