version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: server:${SERVER_VERSION:-latest}
    restart: always
    # Allow docker to access home directory
    user: root
    volumes:
      # Mount a volume for file uploads.
    - type: bind
      source: ${MODELS_DIR?:MODELS_DIR not set}
      target: /var/lib/docker/volumes/filez-models
    - type: bind
      source: ${DATASETS_DIR?:DATASETS_DIR not set}
      target: /var/lib/docker/volumes/filez-datasets
    - type: bind
      source: ${JOBS_DIR?:JOBS_DIR not set}
      target: /var/lib/docker/volumes/filez-jobs
    - type: bind
      source: ${RESULTS_DIR?:RESULTS_DIR not set}
      target: /var/lib/docker/volumes/filez-results
    - .:/var/www/mlab/server
    env_file:
    - .env
    ports:
      # Exposes application port.
    - ${PORT}:${PORT}
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SERVER_HOST: ${HOST}
      SERVER_DB_HOST: ${DB_HOST}
      SERVER_DB_PORT: ${DB_PORT}
      SERVER_DB_USER: ${DB_USER}  
      SERVER_DB_PASS: ${DB_PASS}
      SERVER_DB_BASE: ${DB_BASE}
      SERVER_REDIS_HOST: server-redis

  migrator:
    image: server:${SERVER_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      SERVER_DB_HOST: ${DB_HOST}
      SERVER_DB_PORT: ${DB_PORT}
      SERVER_DB_USER: ${DB_USER}
      SERVER_DB_PASS: ${DB_PASS}
      SERVER_DB_BASE: ${DB_BASE}

  redis:
    image: bitnami/redis:6.2.5
    hostname: "server-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
  
  alembic:
    image: server:${SERVER_VERSION:-latest}
    restart: "no"
    entrypoint: alembic
    container_name: alembic
    volumes:
      - .:/var/www/mlab/server
    working_dir: /var/www/mlab/server
    profiles: ["alembic"]
    networks:
      - default



volumes:
  filez-datasets:
    name: filez-datasets
  filez-jobs:
    name: filez-jobs
  filez-results:
    name: filez-results
