version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: server:${SERVER_VERSION:-latest}
    restart: always
    # Allow docker to access home directory
    user: root
    volumes:
      # Mount a volume for file uploads.
    - type: bind
      source: ${MODELS_DIR?:MODELS_DIR not set}
      target: /var/lib/docker/volumes/filez-models
    - filez-datasets:/var/lib/docker/volumes/filez-datasets
    - filez-jobs:/var/lib/docker/volumes/filez-jobs
    - filez-results:/var/lib/docker/volumes/filez-results
    env_file:
    - .env
    ports:
      # Exposes application port.
    - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_DB_HOST: server-db
      SERVER_DB_PORT: 5432
      SERVER_DB_USER: server
      SERVER_DB_PASS: server@123
      SERVER_DB_BASE: server
      SERVER_REDIS_HOST: server-redis

  migrator:
    image: server:${SERVER_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      SERVER_DB_HOST: server-db
      SERVER_DB_PORT: 5432
      SERVER_DB_USER: server
      SERVER_DB_PASS: server@123
      SERVER_DB_BASE: server

  redis:
    image: bitnami/redis:6.2.5
    hostname: "server-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  filez-datasets:
    name: filez-datasets
  filez-jobs:
    name: filez-jobs
  filez-results:
    name: filez-results
