name: Push to server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.MLAB_SERVER_PATH }}
            git pull
            pip install -r requirements.txt
            docker-compose -f deploy/docker-compose.yml --project-directory . down
            docker-compose -f deploy/docker-compose.yml --project-directory . up --build -d
